name: CI

on:
  push:
    branches: [ master ]
  pull_request:

# TODO test Mac?
jobs:
  linux_make_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scheduler: [nemesis, sherwood, distrib]
        topology: [hwloc, binders, no]
    steps:
    - uses: actions/checkout@v2
    - name: install hwloc
      run: |
        sudo apt-get install hwloc libhwloc-dev
        hwloc-ls --version
    - name: build qthreads
      run: |
        ./autogen.sh
        ./configure --with-scheduler=${{ matrix.scheduler }} --with-topology=${{ matrix.topology }}
        make
    - name: make check
      run: |
        make check

  mac_make_check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        brew install autoconf automake libtool
    - name: install hwloc
      run: |
        brew install hwloc 
        hwloc-ls --version
    - name: build qthreads
      run: |
        ./autogen.sh
        ./configure
        make
    - name: make check
      run: |
        make check
