name: CI

on:
  push:
    branches: [ master ]
  pull_request:

# TODO test Mac?
jobs:
  linux_make_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scheduler: [nemesis, sherwood, distrib]
    steps:
    - uses: actions/checkout@v2
    - name: install hwloc
      run: |
        sudo apt-get install hwloc
        hwloc-ls --version
    - name: build qthreads
      run: |
        ./autogen.sh
        ./configure --with-scheduler=${{ matrix.scheduler }}
        make
    - name: make check
      run: |
        make check
