name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  make_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt-get install hwloc
        hwloc-ls --version
    - name: build qthreads
      run: |
        ./autogen.sh
        ./configure 
        make
    - name: make check
      run: |
        make check
